### ISSUE TITLE
i think they patched it

### ISSUE THREAD

**Issue by Iamcat1230** [ading2210/edpuzzle-answers#1]
im clicking on the bookmark but nothings is popping up

**Comment by ading2210** [comment]
Turns out [this](https://github.com/ading2210/edpuzzle-answers/commit/2c18b08de850ceb57b5511e5648bf6462237e2f6) commit broke the bookmarklet. For whatever reason, setting the script src to a raw.githubusercontent.com didn't work. Re-create the bookmarklet and try again, it should be working now.
