### ISSUE TITLE
Edpuzzle embedded onto dadeschools.schoology.com

### ISSUE THREAD

**Issue by CeyTrez** [ading2210/edpuzzle-answers#10]
My teacher embedded her Edpuzzle assignments onto Schoology, I saw how there was an update for that but it's specifically on a dadeschools.schoology.com link

https://dadeschools.schoology.com/external_tool/2639795867/launch

**Comment by ading2210** [comment]
It should still work fine. The script isn't tied to a specific domain on sites such as Schoology or Canvas.
