### ISSUE TITLE
Thank you! + suggestion

### ISSUE THREAD

**Issue by Nitroandaccounts** [ading2210/edpuzzle-answers#13]
Now, I usually don’t create Issues to thank people, but this helped me so much. I have hour long assignments of stuff I already know, and using this I can’t skip that. The only suggestion I can give is it the pop up maybe show that same video on YouTube (pretty sure Edpuzzle fetches it from YouTube, so you can easily take the url) so we can watch portions of it separately on our own time.

**Comment by ading2210** [comment]
Couldn't you just right click and hit "copy URL?"

**Comment by jasonhe54** [comment]
> Couldn't you just right click on the video and hit "copy URL?"

That would work, except it's going to send you to a different URL that you can't access. Returns a URL from the youtubeeducation.com domain as opposed to youtube.com. Rather simple fix though. Just replace youtubeeducation.com with youtube.com. That'll work.
Example URL: https://www.youtubeeducation.com/watch?v=-somerandomID125
