### ISSUE TITLE
Edpuzzle Video speed not working

### ISSUE THREAD

**Issue by danthekidd** [ading2210/edpuzzle-answers#17]
Edpuzzle Video speed is changing nothing. I am doing this on an assignment from schoology with no questions.

**Comment by ading2210** [comment]
What is the video type? Is it hosted on Youtube or Edpuzzle?

**Comment by carter0nline** [comment]
I'm having the same issue. Normal edpuzzle, appears to be hosted on YouTube. My school blocks Chrome's developer tools for some god forsaken reason.

**Comment by MagicJinn** [comment]
There is a line missing, `player.setPlaybackRate(speed)`, on line 77 of `app/videospeed.js`. Should be an easy fix, not entirely sure why it isn't there.
