### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by ieatwaffles1** [ading2210/edpuzzle-answers#19]
so i got the bookmark and everything but when i click it nothing pops up like ill right click it, double click it, normal and nothing works i even tried the java script one and yes i allowed pop ups and java scripts and allat i have a 50 min edpuzzle bru plsssssssss help

**Comment by ieatwaffles1** [comment]
also the rawgithub link thingy is not blocked on my chromebook

**Comment by ading2210** [comment]
Are you using a school device? If so, the script will not work, since Google disabled bookmarklets on managed devices with Chrome v115.

**Comment by src-ry** [comment]
Works for me, 99% sure it is part of the bookmarklets patch that Google (unfortunately) made. :octocat:

**Comment by RyanFu008** [comment]
sounds like a skill issue!!!

**Comment by xbubbo** [comment]
If your school has blocked javascript within bookmarks (bookmarklets), then you will not be able to use this project.
