### ISSUE TITLE
not working !!!

### ISSUE THREAD

**Issue by ItsZaxo** [ading2210/edpuzzle-answers#22]
when clicked on the bookmark, nothing happened. I deleted the link and put it again and nothing happened pls fix

**Comment by ading2210** [comment]
Are you on a school device or using Chrome with your school account?

**Comment by RyanFu008** [comment]
sounds like a skill issue!!!

**Comment by xbubbo** [comment]
If your school has blocked javascript within bookmarks (bookmarklets), then you will not be able to use this project.

**Comment by ading2210** [comment]
This issue is stale and most likely a duplicate of #14.
