### ISSUE TITLE
Got All Wrong

### ISSUE THREAD

**Issue by Displayeddd** [ading2210/edpuzzle-answers#23]
Clicked on answer all questions and got everything wrong.

**Comment by arandomhooman** [comment]
Ouch. That would be a 1 in my class. 
@ading2210

**Comment by prxxymaster** [comment]
Yep. think they somehow patched it after ages.

**Comment by Displayeddd** [comment]
Thanks

**Comment by Aaaaatk** [comment]
Can u create one for delta math

**Comment by Aaaaatk** [comment]
> I'm working on a fix for this right now. It seems like Edpuzzle finally caught onto this after over a year. 

Can u please create one for AP college board website plzzzzz

**Comment by Aaaaatk** [comment]
Plzzzzz do one for AP College Board AP human geography plzzzzzzz I neeeedd ittt
