### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by User73923** [ading2210/edpuzzle-answers#25]
Hello,
When I use the tool, it lists all the questions and answers, but the correct answer is not underlined. Is there a way to fix this?

**Comment by User73923** [comment]
Does this mean the extension does not work anymore?

**Comment by User73923** [comment]
> edpuzzle has patched the tool

Does this mean the extension does not work anymore?

**Comment by maxhithere** [comment]
unless there is a workaround unfortunately not

**Comment by ading2210** [comment]
This has already been fixed. Jsdelivr wasn't updating it on their CDN so you weren't able to download the updated script.

**Comment by maxhithere** [comment]
> This has already been fixed. Jsdelivr wasn't updating it on their CDN so you weren't able to download the updated script.

Oh really? let me test it out

**Comment by maxhithere** [comment]
> This has already been fixed. Jsdelivr wasn't updating it on their CDN so you weren't able to download the updated script. They've updated it now so the script should work fine.

seems that it still hasn't updated as correct answers are still not being underlined

**Comment by ading2210** [comment]
@maxhithere Try clearing your browser's cache.

**Comment by maxhithere** [comment]
ah it works now. thanks

**Comment by User73923** [comment]
> @maxhithere Try clearing your browser's cache.

It worked when I cleared the browser's cache. Thank you both very much.
