### ISSUE TITLE
Doesn't work on certain edpuzzles

### ISSUE THREAD

**Issue by Rugbeatuno** [ading2210/edpuzzle-answers#3]
I have narrowed the bug down to a specific point, when you make your request to "url...classrooms/classId/students" it will return a request that looks something like this.

```
{teacherAssignments: Array(50), medias: Array(50), projects: Array(0), attempts: Array(50)}
attempts
: 
(50) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
medias
: 
(50) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
projects
: 
[]
teacherAssignments
: 
(50) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
[[Prototype]]
: 
Object
```

The bug occurs when the teacher has ASSIGNED over 50 edpuzzle assignments because the API only returns the first 50. I have tried guessing some payload parameters that could maybe return the next 50 edpuzzles, but I haven't found any that work.

**Comment by ading2210** [comment]
I've known about this for a while. Unfortunately, `/api/v3/assignments/classrooms/CLASSROOM_ID/students/` is the only API endpoint where I can reliably fetch media data that isn't stripped of answers. However, the endpoint only returns the 50 *newest* assignments, so it isn't that big of an issue. 

There's also `/api/v3/media/MEDIA_ID`, but it only works on videos that are public and only if you're not authenticated. I can probably write a patch that requests the second endpoint if the first fails, but I don't really have time for that at the moment. 

If you want to take a look at other potential API endpoints to use, I've actually discovered their entire [private API docs](https://d1htrclywvryi1.cloudfront.net/apidoc/explaineverything/Edpuzzle%20API%20documentation_files/api_data.js
) just chilling on their CDN. I've tried most of them already, but there might be something in there that would work more reliably.

**Comment by ading2210** [comment]
I've fixed this in the latest commit. Turns out adding `?needle=ASSIGNMENT_ID` to the endpoint URL lets us fetch the next page.

**Comment by Rugbeatuno** [comment]
You are a genius, also how did you find their API docs.

**Comment by ading2210** [comment]
Just Google "edpuzzle private api docs" and the second result gives you an index of their CDN. The third item in that list gives you their API docs.

**Comment by Ribun-Bruni** [comment]
> I've known about this for a while. Unfortunately, `/api/v3/assignments/classrooms/CLASSROOM_ID/students/` is the only API endpoint where I can reliably fetch media data that isn't stripped of answers. However, the endpoint only returns the 50 _newest_ assignments, so it isn't that big of an issue.
> 
> There's also `/api/v3/media/MEDIA_ID`, but it only works on videos that are public and only if you're not authenticated. I can probably write a patch that requests the second endpoint if the first fails, but I don't really have time for that at the moment.

I've been using `/api/v3/media/MEDIA_ID` with a teacher account and a teacher token, which is free to make. Without a token, or with a student one, you get 404.

**Comment by ading2210** [comment]
I know using a teacher account also works, but it isn't realistic to expect everyone to create a teacher account just for this.
