### ISSUE TITLE
Fetching Assignments... Error

### ISSUE THREAD

**Issue by HasteBoy** [ading2210/edpuzzle-answers#30]
Its been working for a 1-2 days but randomly started processing The assignement with no response and when i make a new bookmark to re try it gives me the same error 
![aaas](https://github.com/ading2210/edpuzzle-answers/assets/124483741/78c162a1-4fa9-4664-aa01-d15f8c46f172)

**Comment by ading2210** [comment]
Duplicate of #27, which is caused by the Edpuzzle being private.
