### ISSUE TITLE
When is this shit being fixed ???

### ISSUE THREAD

**Issue by smorenitez** [ading2210/edpuzzle-answers#32]
Sorry for the rude language, but DAMN. It's been like what, 3 months? And its still not fixed? Come on, this script had thousands of people using it every day. I get your an indie developer or whatever, but I'm a student with active EdPuzzles that needs to be solved! There are working scripts that lets you skip the video lock thing, it's possible to fix it, so fix it please! If you really can't make the script that finds the answers work, then just use ChatGPT to solve the answers automatically. It's that simple. Please just fix it!!!!

**Comment by ading2210** [comment]
The API endpoint the script used previously was patched to no longer leaked answers, so I had to switch to a different one that didn't work on private Edpuzzles. There isn't really an easy fix for this. Using an LLM to solve every single question is rather costly, so that's out of the question.

**Comment by kxtzownsu** [comment]
![image](https://github.com/ading2210/edpuzzle-answers/assets/116377025/6352df76-0c26-4355-8a7a-b9abd50739ed)

**Comment by ading2210** [comment]
Also, next time maybe don't be rude to maintainers of free software. The people who make this sort of software owe you nothing.

**Comment by smorenitez** [comment]
The AI at AI21 literally gives you $90 in free API bills credit, just make a new account every time the trial runs out or if you run out of credits. @ading2210 Bruh

**Comment by ading2210** [comment]
This script gets around 6k users per day. A paid API is unsustainable with that many users, and I don't ever intend on spending money to maintain this service.

**Comment by FoxMoss** [comment]
> The AI at AI21 literally gives you $90 in free API bills credit, just make a new account every time the trial runs out or if you run out of credits. @ading2210 Bruh

if its easy, just make your own fork.

**Comment by smorenitez** [comment]
@FoxMoss No because it's fucking ridiclous why can't he just do it himself. I told him a free AI API that gives you $90 in API Bills, he can keep creating new accounts every time he runs out of credits and never pay the AI company a dime because they give $90 free credits in API to new accounts, but he likes to stay blind and not do anything. It's actually insane. It's like if Google decided to stop updating chrome and told us "if yall want updates so bad fork chromium and add updates urself" like what???

**Comment by FoxMoss** [comment]
> @FoxMoss No because it's fucking ridiclous why can't he just do it himself. I told him a free AI API that gives you $90 in API Bills, he can keep creating new accounts every time he runs out of credits and never pay the AI company a dime because they give $90 free credits in API to new accounts, but he likes to stay blind and not do anything. It's actually insane. It's like if Google decided to stop updating chrome and told us "if yall want updates so bad fork chromium and add updates urself" like what???

google makes a bullshit amount of money from chrome that lets them reinvest, cheating an api isnt sustainable. just answer questions by actually thinking bro

**Comment by smorenitez** [comment]
> google makes a bullshit amount of money from chrome that lets them reinvest, cheating an api isnt sustainable. just answer questions by actually thinking bro

@FoxMoss Then in that case, he should just fix it, HE HAD THREE WHOLE MONTHS AND NO PROGRESS!!!!! WHAT DO YOU CALL THAT HUH? A GREAT DEVELOPER? NO!!!! I'm serious. They are seriously unreliable. If they don't care about this project they should hire more contributors. But no he wanna stay lazy. Like what is he paying u to be his little bitch ???

**Comment by kxtzownsu** [comment]
> > google makes a bullshit amount of money from chrome that lets them reinvest, cheating an api isnt sustainable. just answer questions by actually thinking bro
> 
> @FoxMoss Then in that case, he should just fix it, HE HAD THREE WHOLE MONTHS AND NO PROGRESS!!!!! WHAT DO YOU CALL THAT HUH? A GREAT DEVELOPER? NO!!!! I'm serious. They are seriously unreliable. If they don't care about this project they should hire more contributors. But no he wanna stay lazy. Like what is he paying u to be his little bitch ???

bro, if you need a edpuzzle script to get more than a 2/10 for your shitty edpuzzles, please go study. edpuzzles really are NOT that hard to do. all it is, is just watching a video, remembering it, and answering a question. thats kinda sad how how much you need to rely on this. if its that big of an issue, just fix it yourself

**Comment by ading2210** [comment]
@smorenitez I've already explained to you why I can't easily fix this, so maybe stop being an asshole about it. It's also pretty damn ironic that you're calling me lazy for providing this software for free, and yet all you've done in this thread is beg.

**Comment by ProgrammerIn-wonderland** [comment]
Fyi, if this was that big of a concern for *you* it wouldn't be that hard for you to make your own mod and use *your own* ***paid*** OpenAI key for this. Do realize, you aren't entitled to *anything* or *anyone's* free time. All the work vk6/ading2210 has put in to this project has been of his own good will and if anything, you should be thankful it *ever* worked. He hasn't monetized this or made money off of this project, nor do I believe he's gained anything from this project for that matter. 

Please, grow up and change as a person. You seriously can't still be thinking that you are entitled to everyone's free time and other people need to fix something simply because you said so, at an age where you can legally use GitHub (13+).

**Comment by arandomhooman** [comment]
^ exactly. You can do it yourself, he does not want to spend 20 hours a week bypassing the API or potentially paying
