### ISSUE TITLE
@TheMemeSniper No because there are like half a millon people who are relying on this project for edpuzzles like this used to get thousands of executions of the js a day but now its 0 cuz its broken and hes too lazy to add afucking update and i am not going to publish my **private** code just because of a lazy developer who is probably gonna steal it cuz its "open source" and @wearrrrr Ur just speaking nonsense bro like what better stuff are they doing, playing basketball with friends or something?? Thats doing nothing for the thousands who used this project every day for edpuzzles, lil bro.

### ISSUE THREAD

**Issue by genericness** [ading2210/edpuzzle-answers#35]
@TheMemeSniper No because there are like half a millon people who are relying on this project for edpuzzles like this used to get thousands of executions of the js a day but now its 0 cuz its broken and hes too lazy to add afucking update and i am not going to publish my **private** code just because of a lazy developer who is probably gonna steal it cuz its "open source" and @wearrrrr Ur just speaking nonsense bro like what better stuff are they doing, playing basketball with friends or something?? Thats doing nothing for the thousands who used this project every day for edpuzzles, lil bro.

your incredibly dumb, how about you go get a fucking life and do your edpuzzle yourself you fucking nerd-degenerate-ass-valorant-player.

_Originally posted by @smorenitez in https://github.com/ading2210/edpuzzle-answers/issues/27#issuecomment-1936841831_

**Comment by TheMemeSniper** [comment]
Many such cases!
