### ISSUE TITLE
This is seriously emberessing for you, VS6k.

### ISSUE THREAD

**Issue by smorenitez** [ading2210/edpuzzle-answers#38]
First of all let me tell you how sorry i feel for you. Sorry for you're pure laziness as a person, as a developer, as a person overall VS. First you havent updated your project in like 6 months, you say your working on updates but lets be real we all know you are probably watching tiktok and doing f**king anything else than updating the project. So you know what? it is ok. I understand lazy people probably have a very low lack of motiviation. But let me tell you I am not like that. I am a hard working, hard coding person. I am only 15 but I have coded 6 months of your code in simply under 8 hours. I have worked 7 hours straight on a new (and better) version of your project that skips the video in under 5 seconds. And you know what? I am also planning on doing ur assignment skipper too where it answers all the assignments for you. and urs doesnt answer open ended questions right? well, mine will soon. Mine (better) project is at https://github.com/smorenitez/Better-EdPuzzle-Skipper/ and like.... Seriously this is like so emberessing for you dude. I am actually sorry for your laziness like what the heck dude??? I spent 20 minutes typing this. So get back to coding or something please... It's clear its a skill that you probably lack off. Also mine is in dark mode and it feels better lol

**Comment by IncognitoTGT** [comment]
@ading2210 use this entitled guys code

**Comment by Xtendera** [comment]
> First of all let me tell you how sorry i feel for you. Sorry for you're pure laziness as a person, as a developer, as a person overall VS. First you havent updated your project in like 6 months, you say your working on updates but lets be real we all know you are probably watching tiktok and doing f**king anything else than updating the project. So you know what? it is ok. I understand lazy people probably have a very low lack of motiviation. But let me tell you I am not like that. I am a hard working, hard coding person. I am only 15 but I have coded 6 months of your code in simply under 8 hours. I have worked 7 hours straight on a new (and better) version of your project that skips the video in under 5 seconds. And you know what? I am also planning on doing ur assignment skipper too where it answers all the assignments for you. and urs doesnt answer open ended questions right? well, mine will soon. Mine (better) project is at https://github.com/smorenitez/Better-EdPuzzle-Skipper/ and like.... Seriously this is like so emberessing for you dude. I am actually sorry for your laziness like what the heck dude??? I spent 20 minutes typing this. So get back to coding or something please... It's clear its a skill that you probably lack off. Also mine is in dark mode and it feels better lol

chill the fck out

**Comment by kxtzownsu** [comment]
![image](https://github.com/ading2210/edpuzzle-answers/assets/116377025/d60c4f37-372b-40b5-8b90-5b08c16288c4)

**Comment by genericness** [comment]
pookie @smorenitez you got your own youtube video https://youtu.be/lJvvAgzKKc0?si=UmCiXmnsP0oqzBav

**Comment by kxtzownsu** [comment]
> pookie @smorenitez you got your own youtube video https://youtu.be/lJvvAgzKKc0?si=UmCiXmnsP0oqzBav

the rare kxtz appearance at the end 🐳

**Comment by genericness** [comment]
you should chat with us and the devs directly in discord.gg/unblock

**Comment by IncognitoTGT** [comment]
the only "emberessing" thing is how you are acting so arrogant and entitled to an open-source dev's code. Maybe you should fork it, and nicely tell him rather than writing a yappuccino about how "lazy" ading2210 is. 

@ading2210 is not your servant omg.

**Comment by genericness** [comment]
my name is akane, mention me in there

@smorenitez 
https://discord.gg/unblock

**Comment by builtbyvys** [comment]
this is kinda sad vS6k

**Comment by LolzTheDev** [comment]
> First of all let me tell you how sorry i feel for you. Sorry for you're pure laziness as a person, as a developer, as a person overall VS. First you havent updated your project in like 6 months, you say your working on updates but lets be real we all know you are probably watching tiktok and doing f**king anything else than updating the project. So you know what? it is ok. I understand lazy people probably have a very low lack of motiviation. But let me tell you I am not like that. I am a hard working, hard coding person. I am only 15 but I have coded 6 months of your code in simply under 8 hours. I have worked 7 hours straight on a new (and better) version of your project that skips the video in under 5 seconds. And you know what? I am also planning on doing ur assignment skipper too where it answers all the assignments for you. and urs doesnt answer open ended questions right? well, mine will soon. Mine (better) project is at https://github.com/smorenitez/Better-EdPuzzle-Skipper/ and like.... Seriously this is like so emberessing for you dude. I am actually sorry for your laziness like what the heck dude??? I spent 20 minutes typing this. So get back to coding or something please... It's clear its a skill that you probably lack off. Also mine is in dark mode and it feels better lol

bro mine better project must be suuuuper emberessing for you dude. ading2210 wil lose so much motiviation and wil go back to watching tiktok!!! yuo must have al the skils that ading2210 lacks!!!

**Comment by LolzTheDev** [comment]
> this is kinda sad vS6k

vs6k must be crying right now

**Comment by IncognitoTGT** [comment]
He has way better stuff to do than helping students cheat. Cry. Cope. Seethe.

**Comment by DraidS** [comment]
> First of all let me tell you how sorry i feel for you. Sorry for you're pure laziness as a person, as a developer, as a person overall VS. First you havent updated your project in like 6 months, you say your working on updates but lets be real we all know you are probably watching tiktok and doing f**king anything else than updating the project. So you know what? it is ok. I understand lazy people probably have a very low lack of motiviation. But let me tell you I am not like that. I am a hard working, hard coding person. I am only 15 but I have coded 6 months of your code in simply under 8 hours. I have worked 7 hours straight on a new (and better) version of your project that skips the video in under 5 seconds. And you know what? I am also planning on doing ur assignment skipper too where it answers all the assignments for you. and urs doesnt answer open ended questions right? well, mine will soon. Mine (better) project is at https://github.com/smorenitez/Better-EdPuzzle-Skipper/ and like.... Seriously this is like so emberessing for you dude. I am actually sorry for your laziness like what the heck dude??? I spent 20 minutes typing this. So get back to coding or something please... It's clear its a skill that you probably lack off. Also mine is in dark mode and it feels better lol

it aint working bro

**Comment by genericness** [comment]
![Screenshot 2024-02-10 at 8 59 56 PM](https://github.com/ading2210/edpuzzle-answers/assets/107654710/d7e6480e-70ff-4555-a34d-da7eb594f7a0)

**Comment by DraidS** [comment]
bro what

**Comment by crazycrystals** [comment]
chatgpt spent 20watts generating this*

**Comment by miikart** [comment]
:whale:

**Comment by IncognitoTGT** [comment]
This is seriously emberessing for you, smorenitez.

**Comment by LolzTheDev** [comment]
i feel terible for vsk6 becuase smorenitz just maked a project much beter than vsk6's

**Comment by GamerFromGamerTown** [comment]
omg hes so lazy there is good (bettr) project

how emberessing

**Comment by kxtzownsu** [comment]
> omg hes so lazy there is good (bettr) project
> 
> how emberessing

bro what better project, also nice github alt @smorenitez 
the code is literally skidded from vk6 (@ading2210)

**Comment by LolzTheDev** [comment]
> > omg hes so lazy there is good (bettr) project
> > how emberessing
> 
> bro what better project, also nice github alt @smorenitez the code is literally skidded from vk6 (@ading2210)

i think that was just satire

**Comment by Koranir** [comment]
This man worked for _7 hours straight_ on a new (and better) version of vs6k's project with vengeance in his heart, and you all are _laughing_ at and _'emberessing'_ him?

Count me in.

**Comment by LolzTheDev** [comment]
> This man worked for _7 hours straight_ on a new (and better) version of vs6k's project with vengeance in his heart, and you all are _laughing_ at and _'emberessing'_ him?
> 
> Count me in.

he literally copied and pasted a file from this repo

**Comment by LolzTheDev** [comment]
fym "better" lmao

**Comment by kxtzownsu** [comment]
Guys, please stop sending messages in here. Aub already gave us a warning because he joined the Discord. The issue is closed, leave it that way.

**Comment by Koranir** [comment]
> This script will skip EdPuzzle videos by unlocking the video progress bar. This was made becasue vs6k was too lazy to update his own project... it's whatever though, you can always rely on us :) We gaarenetee at least 6 months of updates on our projects. This project was made Feburary 2024.

Remind me in 6 months, I guess.

**Comment by TheMarksman-ES** [comment]
> > This script will skip EdPuzzle videos by unlocking the video progress bar. This was made becasue vs6k was too lazy to update his own project... it's whatever though, you can always rely on us :) We gaarenetee at least 6 months of updates on our projects. This project was made Feburary 2024.
> 
> Remind me in 6 months, I guess.

_Coughing in Endless Sky updating after two years and having a hell of a lot of contributions during that period._

**Comment by IAGOnGithub** [comment]
he's still babyraging this is hilarious

**Comment by lvxnull** [comment]
me when they steal my code (died of emberessing)

**Comment by TBNRAubrey** [comment]
holy fucking shit 3 threads in and you're still coping LMAOOOOOOO

**Comment by Percslol** [comment]
i cant believe you would do this VS6K. this is so emberessing for you.

**Comment by IncognitoTGT** [comment]
so emberressing
also hi aub

**Comment by BomberFish** [comment]
damn did i really miss out on this one

**Comment by IAGOnGithub** [comment]
He's still getting trolled in his repo, which steals code I may add

**Comment by 3kh0** [comment]
🍿

**Comment by EnterTheVoid-x86** [comment]
and here's the yapper
