### ISSUE TITLE
This shit is broken lmao

### ISSUE THREAD

**Issue by fortnite2022x** [ading2210/edpuzzle-answers#39]
I dont know who you are but like i seen u havent put a update in months dude and i found a new hack/mod menu for edpuzzle and its by this dude named smores or smorenitez idk how u spell it but like what the heck dude lol like this one is like better? Why are you abandonded your project dude https://github.com/smorenitez/Better-EdPuzzle-Skipper Like look at this its updated literally every day

**Comment by thonkinator** [comment]
![image](https://github.com/ading2210/edpuzzle-answers/assets/51034477/778ee353-ac50-4e1c-9cf2-988bf64ac9ac)

**Comment by thonkinator** [comment]
guys i think this account might perhaps maybe just be perhaps affiliated with the github account known as "smorenitez"

**Comment by CoolElectronics** [comment]
is mf trying to get shit raided again??

**Comment by IAGOnGithub** [comment]
Smorenitez's code does not work, and even if it did, it's just stolen from here anyway.
