### ISSUE TITLE
Doesn't even open anymore

### ISSUE THREAD

**Issue by RANSOMIC** [ading2210/edpuzzle-answers#53]
at first it would open and then say fetching answers now i just click on it for there to be no response. I'm not sure why this issue is going on but it's been like this for a minute.

**Comment by xbubbo** [comment]
If your school has blocked javascript within bookmarks (bookmarklets), then you will not be able to use this project.

**Comment by lvxnull** [comment]
have you tried pasting `fetch("https://cdn.jsdelivr.net/gh/ading2210/edpuzzle-answers@latest/script.js").then(r => r.text()).then(r => eval(r))` into the browser console?

**Comment by ading2210** [comment]
This issue is stale and most likely a duplicate of #14 anyways.
