### ISSUE TITLE
media_source youtube goes nowhere in your code

### ISSUE THREAD

**Issue by Zonk526** [ading2210/edpuzzle-answers#55]
I checked your code and went to the videospeed.js file and saw that when you check if the source is youtube it goes through all these item and keys in for loops but eventually goes no where and stops at an empty function

**Comment by Zonk526** [comment]
also ive found that the way to skip the video is to send that timeInterval value to that api 11 times from 0-10 and after each fetch also send a fetch to the attempt api for your assignment so something like this 

getAttempt().then(attempt => {
      for (let i = 0; i <= 10; i++) {
           setTimeout(() => {
                getToken().then(token => {
                     finishVid(attempt._id, token, i);
                     getAttempt(); // to update the attempt data
                });
                
                if (i == 10) setTimeout(() => {
                     window.location.reload();
                }, 3000);
           }, i * 5000);
      }
});

obviously replace stuff to make it work with your code but this did work for me

**Comment by ading2210** [comment]
I looked over my code for the video speed changer and the method it uses to set the video speed is correct.
