### ISSUE TITLE
Has barely anything to do with edpuzzle

### ISSUE THREAD

**Issue by Spideyboyjk2** [ading2210/edpuzzle-answers#59]
Um, so ur buddy toucan banned me out of the discord group, but I am in fact 14, so yeah, he said I was not. I'm in eighth grade. So can you please unban me? I didn't know any other way to get to you, so yeah, sorry. Once again I'm very sorry about this. Sure I made my account when I was not of age but I am now of age so yea... :_)

**Comment by Spideyboyjk2** [comment]
I closed it so it wouldn't bother you. But can you respond when u have some time?

**Comment by VenomousSteam81** [comment]
imagine

**Comment by ading2210** [comment]
I've unbanned you, though next time you should probably just send an email instead.

**Comment by Spideyboyjk2** [comment]
Alright thanks😁
