### ISSUE TITLE
Private Videos Issue

### ISSUE THREAD

**Issue by UnpaidUnigen** [ading2210/edpuzzle-answers#60]
It says in the code should work on Private videos as well, but it doesn't for me. I can speed up the video, but the right answers don't show, and neither do the skip video and answer questions buttons work.
![Screenshot 2024-03-20 172717](https://github.com/ading2210/edpuzzle-answers/assets/164256271/5283287f-98af-4284-b5f2-c2ad6413157a)

**Comment by ading2210** [comment]
This is a duplicate of #57
