### ISSUE TITLE
API moved from v3 to v4

### ISSUE THREAD

**Issue by helloyork** [ading2210/edpuzzle-answers#63]
Edpuzzle's API endpoints are moved from v3 to v4, for example for **https://edpuzzle.com/api/v3/media** attempts should be migrated as
**https://edpuzzle.com/api/v4/media_attempts/<ASSIGNMENT_ID>/watch**
I didn't run a full test, this is just my guess
Currently the tool is stuck at the Fetch Assignment step, as requests for the original v3 endpoint return 403 Forbidden

**Comment by helloyork** [comment]
btw, send POST request to 
**"https://edpuzzle.com/api/v4/media_attempts/<ASSIGNMENT_ID>/watch"**
with body
"body": "{\"timeIntervalNumber\":10}",
  "mode": "cors",
  "credentials": "include"
and include "x-csrf-token" in headers

**Comment by ading2210** [comment]
![image](https://github.com/user-attachments/assets/25eb346c-4cd4-4d65-8c70-a837a8f48ce5)

The v3 API definitely still works for me. 

Besides, for the thing you mentioned, the script is already using the v4 endpoint:
![image](https://github.com/user-attachments/assets/627f6df0-8663-451b-9899-a89a43431334)

The problem with the 403 forbidden error is a completely different issue where it's unable to find the answers for a private edpuzzle. See #57
