### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by yibbbbbb** [ading2210/edpuzzle-answers#9]
I've attempted to use the newest version of the bookmarklet and while it creates the pop up the correct answers are not underlined and the skip video does not work

**Comment by ading2210** [comment]
What device are you using the script on? Also, if possible, please add screenshots which show the issue.

**Comment by Yerthesweat** [comment]
Chrome book and I will attach screenshots shortly

**Comment by ading2210** [comment]
Is raw.githubusercontent.com blocked for you?

**Comment by Yerthesweat** [comment]
Yes and it has been fora while but I can still get bookmarklets onto the computer

**Comment by ading2210** [comment]
Yeah, so the script loads its resources off of raw.githubusercontent.com, so if that's blocked then it won't work.

**Comment by Yerthesweat** [comment]
Is there anyway to get around this?

**Comment by ading2210** [comment]
For now though, put `document.dev_env = "https://cdn.jsdelivr.net/gh/ading2210/edpuzzle-answers@latest"; ` at the beginning of the bookmarklet after the `javascript: ` part. That'll tell the script to fetch all assets from Jsdelivr instead of Github.

**Comment by ading2210** [comment]
> For now though, put `document.dev_env = "https://cdn.jsdelivr.net/gh/ading2210/edpuzzle-answers@latest"; ` at the beginning of the bookmarklet after the `javascript: ` part. That'll tell the script to fetch all assets from Jsdelivr instead of Github.

@Yerthesweat Can you confirm whether or not this works?

**Comment by Yerthesweat** [comment]
Havnt had to use edpuzzle recently but I will update when i do
